### ISSUE TITLE
webroot variable in start.sh never used

### ISSUE THREAD

**Issue by woopstar** [ngineered/nginx-php-fpm#104]
The `webroot` variable in `start.sh` is never used. If you define a custom webroot the variable containing it is never used.

I suspect that these chowns `chown -Rf nginx.nginx /var/www/html` should be changed to `chown -Rf nginx.nginx $webroot`

Also, the RUN_SCRIPTS depends on the default webroot and not the custom webroot. Or I suspect that because it's hardcoded to` if [ -d "/var/www/html/scripts/" ]; then` . It should prolly be changed to `if [ -d "$webroot/scripts/" ]; then`

**Comment by richarvey** [comment]
so $webroot at the moment always has to be a sub folder in /var/www/html hence the hard coding. Its something that needs fixing at some point.
