### ISSUE TITLE
logfile remote IP address using nginx-proxy

### ISSUE THREAD

**Issue by fflo** [ngineered/nginx-php-fpm#106]
Hi,

thanks for this great image 👍

I'm using it in combination with jwilder/nginx-proxy and JrCs/docker-letsencrypt-nginx-proxy-companion - that's awesome!

To get nginx-wordpress-docker logging the correct remote IP address using jwilder/nginx-proxy I had to add the following to lines to default.conf:

real_ip_header X-Forwarded-For;
set_real_ip_from 172.16.0.0/12;

Maybe you have an idea howto include this feature to your official image, i.e. allowing to setup the environment variables REAL_IP_HEADER and REAL_IP_FROM in case the container is running behind a proxy.

**Comment by richarvey** [comment]
That sounds like a good idea. We'll look at integrating that.

**Comment by richarvey** [comment]
This has been added and we are now pushing out a new version
