### ISSUE TITLE
Support for PHP 7.1

### ISSUE THREAD

**Issue by TheCodeEngine** [ngineered/nginx-php-fpm#107]
Thanks for this great Image 👍 

It is possible to support PHP 7.1 ?

**Comment by richarvey** [comment]
I'll look into it. It'll mean building from code so I'll look at tweaking things about.

**Comment by richarvey** [comment]
This is now underway

**Comment by richarvey** [comment]
@TheCodeEngine please try 

```
docker pull richarvey/nginx-php-fpm:php71
```

### Things left to do: 

- test all the scripts
- reduce image size
- update doc's showing how to install php modules

**Comment by richarvey** [comment]
Spotted a few issues with the sed commands. Will fix shortly

**Comment by richarvey** [comment]
Issues should be fixed, I've sucessfully deployed a site through this and modified variables etc etc

**Comment by richarvey** [comment]
7.1 is now the default
