### ISSUE TITLE
Passphrase for key if using SSH for GIT/Bitbucket

### ISSUE THREAD

**Issue by x86fantini** [ngineered/nginx-php-fpm#110]
Hi, i'm tring to use ssh to autodownload my repo from bitbucket. i have managed to add all variables and at boot, my container tries to download repo but get stuck. After second/third restart i can log in and if i issue /usr/bin/pull, it asks for passfrase

>
/ # /usr/bin/pull 
Enter passphrase for key '/root/.ssh/id_rsa':  
>

i'm using a Mac 10.12.3 Sierra, and i have base64 command via "brew" that does not support the "base64 -w" switch and i must use "base64 -d 0 /Users/_my_user_name_/.ssh/id_rsa.pub"

since i do not use any password on my ssh key (my key is passwordless) i presume there is something wrong when passing the base64 encoded key to container.

thx
S

**Comment by x86fantini** [comment]
i have managed to solve it.

docs says

`base64 -w 0 /path_to_your_key`

but it's unclear, i mean it's not 100% failproof.

i was running `base64 -w 0 .ssh/id_rsa.pub` but all i needed is to run `base64 -w 0 .ssh/id_rsa`

now it's working, i suggest to edit the manual , if this can help

S

**Comment by richarvey** [comment]
good idea I'll clarify this
