### ISSUE TITLE
make release versions tags

### ISSUE THREAD

**Issue by atlasnetwork** [ngineered/nginx-php-fpm#114]
Occasionally, using the latest tag, new updates will break existing deployments.  For example, the addition of REAL IP / X-Forwarded-For Headers for deployments behind ELBs caused some issues.  

Using version numbers as tags for docker image builds would allow for people to update on their own schedule, and those that wish can stay on the latest tag.

**Comment by richarvey** [comment]
Agreed, this is on my todo, i'm looking to do github versions and also open an LTS tag in docker hub that will be semver , however I'm open to suggestions.

**Comment by atlasnetwork** [comment]
That sounds great, thank you.  If you are looking for a good example, I
feel that https://github.com/sameersbn/docker-gitlab /
https://hub.docker.com/r/sameersbn/gitlab/ has done a good job of it.

Thanks for sharing this project.

**Comment by richarvey** [comment]
@sameerbn does great work :) will take a look

**Comment by richarvey** [comment]
This is underway, starting with 1.1.1 with 1.1.2 to follow shortly. The documentation as of 1.1.2 will also explain the versioning.
