### ISSUE TITLE
php 7.0

### ISSUE THREAD

**Issue by aamche** [ngineered/nginx-php-fpm#119]
Is it possible to keep an php 7.0 version. Php 7.1 implements some changes that breaks things.

**Comment by aamche** [comment]
Opps, my bad. Seems the php7 tag is still valid. Perhaps php7 and php5 tags could go on the versioning doc.

**Comment by aamche** [comment]
php 7.1 breaks mcrypt_create_iv in codeigniter which could be a problem.

**Comment by richarvey** [comment]
The tags remain however we aren't actively supporting them due to workload hence not being on the versioning document.

**Comment by aamche** [comment]
Thanks Richard, for all your hard work.

I'll close this. I've made the developers upgrade there stuff to from 7.0 and 7.1.
