### ISSUE TITLE
Custom rewrites and other modifications

### ISSUE THREAD

**Issue by jnovack** [ngineered/nginx-php-fpm#120]
Right now, the `default.conf` and `nginx.conf` are static.

Rather than export your pre-generated `confs` and overwrite them, I was hoping we could allow for include directives inside the conf files so we can optionally inject customizations.

**nginx.conf**
```
http {
    ...
    include /etc/nginx/snippets/http.conf
    ...
}
```

**default.conf**
```
server {
    ...
    location / {
        include /etc/nginx/snippets/location.conf
        ...
    }
    ...
    include /etc/nginx/snippets/server.conf
}
```

This way, I can mount my snippets volume and have nginx completely customized.

Example use case is any site that makes use of custom url rewriting.  I have a site that uses:

* /verb1/var1/var2
* /verb2/var1/
* /verb3/var1/var2

That's unable to run without custom modification of `default.conf`.  I know I can overwrite it, but why do that when we can use **includes** (and what if your `default.conf` changes in the next version??)

**Comment by richarvey** [comment]
You can override the nginx config

https://github.com/ngineered/nginx-php-fpm/blob/master/docs/nginx_configs.md

Ric
