### ISSUE TITLE
/var/www/html nuke may be overkill

### ISSUE THREAD

**Issue by jnovack** [ngineered/nginx-php-fpm#121]
This makes it EXTREMELY hard to pre-populate the `/var/www/html/` directory with volumes...

https://github.com/ngineered/nginx-php-fpm/blob/master/scripts/start.sh#L40

**start.sh**
```
   # Remove the test index file
   rm -Rf /var/www/html/*
```

I can't `docker volume` in any files (like a `config.php`) or any directories into `/var/www/html/`.

I would humbly propose `rm -Rf /var/www/html/index.php`.

**Comment by iSDP** [comment]
I'd rather like to see an environment variable (USE_GIT)

**Comment by richarvey** [comment]
@iSDP i like that idea if I set up USE_GIT=1 as default and nothing changes in the script but if you set USE_GIT=0 we dont

```
   # Remove the test index file
   rm -Rf /var/www/html/*
```

**Comment by iSDP** [comment]
Sounds fine to me :)

**Comment by richarvey** [comment]
New flag will be REMOVE_FILES=0

**Comment by iSDP** [comment]
Rather hoped for the ability to completely shut off the Git functionality.

It's really annoying to have to make a gazillion commits to update the files on my server properly =[

**Comment by jnovack** [comment]
@richarvey Excellent, thank you!

And I kinda agree with @iSDP @iSDP Are you just mounting in your `/var/www/html`, if so, this command neither helps nor hurts because the conditional isn't running.

If you are talking about developing within the container, then you'll definitely WANT to use a mount.  Edit locally, refresh in container.  But to stop it from removing the `/var/www/html/*` files, just make a directory called `/.git`, or don't use `GIT_REPO`.  Either one of those will prevent the conditional from running.

**Comment by iSDP** [comment]
@jnovack what if you want to track your code in git but don't want the container to do it's git stuff then?

Explicit defining is always better than implicitly through a folder's existence.

**Comment by jnovack** [comment]
> what if you want to track your code in git but don't want the container to do it's git stuff then?

Mount the *git-versioned* source directory on your host as `/var/www/html` read-only and DO NOT set any `GIT` variables.  The `start.sh` script finds the `/var/www/html/.git/` directory, and does nothing else.
