### ISSUE TITLE
Adapt CPU and memory limit to your current infrastructure

### ISSUE THREAD

**Issue by raimonbosch** [ngineered/nginx-php-fpm#122]
Hi,

Is it possible to adapt the worker_processes to the number of CPUs you have available? Also it would be great if you could adapt your php memory limits to your RAM available.

I guess there are several solutions that could work well. Here is an example for memory tuning  http://drupalwxt.github.io/performance/apache-fpm/

Thanks in advance,

**Comment by richarvey** [comment]
I'll look into this, we might need a flag to enable it to stop it automatically using everything on a system. In the meantime you can use custom nginx configs

**Comment by mralexho** [comment]
@raimonbosch since nginx 1.3.8+, assigning worker_processes are no longer required. Nginx will automatically figure that out.

https://nginx.org/en/docs/ngx_core_module.html#worker_processes
