### ISSUE TITLE
apt-get: command not found ?

### ISSUE THREAD

**Issue by alex-chan** [ngineered/nginx-php-fpm#129]
`docker run richarvey/nginx-php-fpm`
then run `docker exec -it keen_thompson bash`
in docker: `bash-4.3# apt-get
bash: apt-get: command not found `

**Comment by richarvey** [comment]
HI @alex-chan the image runs alpine linux, try using:

```apk search <PACKAGE_NAME>```

and

```apk add <PACKAGE_NAME>```
