### ISSUE TITLE
would this image support oci8  for oralce

### ISSUE THREAD

**Issue by cooka** [ngineered/nginx-php-fpm#131]
Oracle db is widely used, it would be great to support oci out-of-box. 

install oci separately is complicated.   

Thanks.

**Comment by lukescammell** [comment]
Apologies to the creator if I’m wrong on this, but I think this request is slightly out of scope for this particular project. Perhaps take a look at this instead?

https://hub.docker.com/r/unitekgsteam/nginx-php-fpm-oci8/
