### ISSUE TITLE
Looks like an issue with php

### ISSUE THREAD

**Issue by arocki7** [ngineered/nginx-php-fpm#132]
As usual, I deployed with the latest version and I got php errors in my web page.

PHP logs were not generating either.

**Comment by richarvey** [comment]
can you show some output? screenshot maybe?

**Comment by arocki7** [comment]
Hi Ric,

Problem is due to PHP5 to 7 upgrade. It has the explanation in the following links. I have similar issues with session as well.

https://github.com/symfony/symfony/issues/18574

https://github.com/bcit-ci/CodeIgniter/issues/4830

https://github.com/joomla/joomla-cms/issues/7143

Thanks.

Regards,
Arockiasamy

**Comment by nalsas** [comment]
Hi, I also run into session issues with this version of php7.1.2.  After investigation, i think the problem could related to the php issue below: 

[If getrandom syscall is unavailable (ENOSYS), try to fallback on /dev/urandom #2385](https://github.com/php/php-src/pull/2385)

FYI, I tried upgrade php7.1.2 to php7.1.3, then the session issue has gone. 

Thanks.

**Comment by arocki7** [comment]
I tried to upgrade and test with 7.1.3 - no luck.

I used the docker image tag php7 and it worked. Not sure how the future going to be with PHP.

Thanks.

**Comment by richarvey** [comment]
Upgrading to 7.1.3 now, this seems an upstream issue. As soon as 7.1.4 image is released I'll bump again
