### ISSUE TITLE
Anyone managed to run this on osx?

### ISSUE THREAD

**Issue by jamiegood** [ngineered/nginx-php-fpm#137]
My docker ps $DOCKER_ID gives "IPAddress": "172.17.0.2"

However that IP times out in the browser.

Though if I ssh in to the container I can curl http://localhost and see my PHP output. 

Any ideas?

**Comment by jamiegood** [comment]
Ok so if i put -p 80:80 to the docker run command like this. it works.

docker run --p 80:80- d -e 'GIT_EMAIL=email_address' -e 'GIT_NAME=full_name' -e 'GIT_USERNAME=git_username' -e 'GIT_REPO=github.com/project' -e 'GIT_PERSONAL_TOKEN=<long_token_string_here>' richarvey/nginx-php-fpm:latest

:

**Comment by chrsc** [comment]
This helped me thanks.
