### ISSUE TITLE
Add xdebug (disabled)

### ISSUE THREAD

**Issue by that0n3guy** [ngineered/nginx-php-fpm#138]
Could you add xdebug to this?   A `docker-php-ext-enable xdebug` doesn't work without running this first:

```
apk upgrade --update && apk add autoconf gcc musl-dev linux-headers libffi-dev augeas-dev python-dev make
pecl install xdebug
```
The command `pecl install xdebug` would be super easy to add to your dockerfile.

Should probably add an env var for `XDEBUG=1` so its enabled on the startup script as well.

**Comment by llbbl** [comment]
@that0n3guy Hey thanks very much for this. I tried adding gcc and autoconf but was missing a bunch of other stuff that pecl needed. 

I got this working locally by creating a new repo and my own Dockerfile and Dockerfile.development with docker-compose.yml file. 

This is what top of Dockerfile.development looks like now thanks to you!

```
FROM richarvey/nginx-php-fpm:latest

RUN apk upgrade --update && apk add autoconf gcc musl-dev linux-headers libffi-dev augeas-dev python-dev make
RUN pecl install xdebug
```

**Comment by that0n3guy** [comment]
@llbbl Glad it worked for you.    This is my local dev dockerfile file:

```
FROM richarvey/nginx-php-fpm:1.2.0
MAINTAINER Peter Olson <that0n3guy@users.noreply.github.com>

COPY ./ /var/www/html/

# install xdebug
RUN apk upgrade --update && apk add autoconf gcc musl-dev linux-headers libffi-dev augeas-dev python-dev make
RUN pecl install xdebug

# cleanup
RUN apk del gcc musl-dev linux-headers libffi-dev augeas-dev python-dev
```

You can see I don't copy the xdebug.so file over yet.    I do that in a script.  I have a script called 03-enable-xdebug.sh that looks like:

```
#!/bin/bash

XdebugFile='/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'

# THIS ERROR is OK! You can ignore it:
#   /usr/local/bin/docker-php-ext-enable: line 83: nm: not found

# enable xdebug
if [[ "$ENABLE_XDEBUG" == "1" ]] ; then
  if [ -f $XdebugFile ]; then
  	echo xdebug already installed.
  else
  	echo "enabling xdebug";
		docker-php-ext-enable xdebug
		# see if file exists
		if [ -f $XdebugFile ]; then
			# See if file contains xdebug text.
			if grep -q xdebug.remote_enable "$XdebugFile"; then
				echo "Xdebug already enabled... skipping"
			else
			    echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > $XdebugFile # Note, single arrow to overwrite file.
				echo "xdebug.remote_enable=1 "  >> $XdebugFile
				echo "xdebug.remote_log=/tmp/xdebug.log"  >> $XdebugFile
				echo "xdebug.remote_autostart=false "  >> $XdebugFile # I use the xdebug chrome extension instead of using autostart
				# NOTE: xdebug.remote_host is not needed here if you set an environment variable in docker-compose liek so `- XDEBUG_CONFIG=remote_host=192.168.111.27`.
				#       you also need to set an env var `- PHP_IDE_CONFIG=serverName=docker`
			fi
		fi
  fi
else
	if [ -f $XdebugFile ]; then
		echo "disabling xdebug" 
	  rm $XdebugFile
	fi
fi

```

That way you can enable it with an environment variable `ENABLE_XDEBUG = 1`

Then in my docker-compose file I have some env vars:
```
      - ERRORS=1
      - RUN_SCRIPTS=1
      - ENABLE_XDEBUG=1
      - XDEBUG_CONFIG=remote_host=192.168.1.7
      - PHP_IDE_CONFIG=serverName=docker
```

**Comment by llbbl** [comment]
@that0n3guy that is much better way to do it. Good job. You should fork and submit a PR!!  Thank you for your contributions. 👍

**Comment by richarvey** [comment]
has anyone got a PR for this?

**Comment by llbbl** [comment]
@richarvey I didn't have chance to do it yet. What was your decision regarding this feature, supported by extending your base image?

**Comment by that0n3guy** [comment]
@richarvey I added a PR.    I'm building now and will test it when its done.   

One thing I don't know about is why you have two `apt add` sections in the dockerfile.   Its probably my lack of experience with alpine.    Should I stick my `pecl install xdebug` in the `apt add @testing` section or the `app add --virtual` section... does it even matter?

**Comment by mathieutu** [comment]
Hi @that0n3guy,
I'm trying to understand how it can work because I'm doing the same on my own. In fact supervisord doesn't propagate the env variables to services, so the `XDEBUG_CONFIG=remote_host=192.168.1.7` and `PHP_IDE_CONFIG=serverName=docker` can't be passed to php. (see https://stackoverflow.com/questions/31069834/using-docker-environment-e-variable-in-supervisor)

I had to make something like that in my start.sh: 
```
echo "xdebug.idekey=${XDEBUG_IDEKEY:-PHPSTORM}" >> $XdebugFile
echo "xdebug.remote_host=$XDEBUG_REMOTE_HOST" >> $XdebugFile
```

and I can't easily propagate the PHP_IDE_CONFIG variable, so I need to set a custom server_name in nginx.

Do you have any idea about this ?

**Comment by llbbl** [comment]
@mathieutu Environment variables, you have to pass it on the command line via -e parameter or use docker-compose to make it easier.  Did you try this? Not sure what supervisord has to do with this. I know Xdebug can be a tricky to setup even without trying to do in a container!

**Comment by that0n3guy** [comment]
@mathieutu llbbl is right... I don't know why you are messing with supervisord for xdebug.

Here is a docker-compose file with the env var examples: https://github.com/oncalladvisors/octobercms-nginx-docker/blob/61e389f447b2dede0a93c57abbddbe7beadcd37c/docker-compose-dev.yml  (point in time link since that repo will change over time)

**Comment by that0n3guy** [comment]
Also, make sure you're on 1.3.3 or newer.. 1.2.0 doesn't have xdebug, my dev just did that to himself the other day :).

**Comment by mathieutu** [comment]
Hi, yeah I know this is about env variable, and I know how docker works. BUT this image use supervisord to launch nginx and php-fpm. (see https://github.com/richarvey/nginx-php-fpm/blob/master/conf/supervisord.conf). 

And supervisord does not propagate automatically environment variables. So, if you look at the $_ENV of php, you should not find your variables.  

An example here: https://stackoverflow.com/questions/43326154/xdebug-inside-docker-container-ignoring-xdebug-config-environment-variable

**Comment by that0n3guy** [comment]
@mathieutu  Have you tested this or are you asking out of theory?  

Environment variables ARE passed to php, here is a video showing it: https://goo.gl/tCkspc

If yours is not, maybe you have an odd nginx config thing going on?

**Comment by mathieutu** [comment]
@that0n3guy Thank you so much for this video, it's very clear.
I will definitely try to understand how it's possible and why it's working here and not on my side.
I let you know my conclusions when I'll have a bit of time.
