### ISSUE TITLE
Add support for healthchecks

### ISSUE THREAD

**Issue by SamMousa** [ngineered/nginx-php-fpm#145]
It would be nice to support a healthcheck URL that is configured in NGINX to always return a http `200`.

**Comment by richarvey** [comment]
Surely always returning a 200 negates the point of a healthcheck. Your application could be erroring and you would want that to fail the healthcheck. I think this would be better to include a health check in your code, rather than a generic 200 block.

**Comment by richarvey** [comment]
Closing after after 7 days
