### ISSUE TITLE
Composer install order

### ISSUE THREAD

**Issue by SamMousa** [ngineered/nginx-php-fpm#146]
Composer install should be run after custom scripts have been run.

These custom scripts could for example:
- Install dependencies that the app requires in `composer.json` (php extensions).
- Install global composer plugins `fxp-composer-asset-plugin`.

**Comment by hkeio** [comment]
Maybe we can also add a config flag so we can decide if we want dev packages to be installed? I could open a new issue and create PR for this.

**Comment by hkeio** [comment]
I created a pull request for this: https://github.com/ngineered/nginx-php-fpm/pull/158

**Comment by richarvey** [comment]
Hey could you rejig your PR so it works against the latest version then I'll get it merged.

Cheers Ric

**Comment by richarvey** [comment]
This should be fixed in 1.3.2
