### ISSUE TITLE
Composer Install Erases Local Dev Dependencies

### ISSUE THREAD

**Issue by esetnik** [ngineered/nginx-php-fpm#163]
See https://github.com/ngineered/nginx-php-fpm/blob/79efb3170bc5fa177c50bb5719b7a2cb90c37ee3/scripts/start.sh#L65

With a local development source volume mount like:
```
volumes:
  .:/var/www/html
```
The `start.sh` script erases the local dev dependencies.

**Comment by richarvey** [comment]
Theres a new flag in 1.3.2 APPLICATION_ENV set this to development to prevent this happening.
