### ISSUE TITLE
iconv not allowed

### ISSUE THREAD

**Issue by brendaniel** [ngineered/nginx-php-fpm#166]
Hi @richarvey 

When I try to use this code in the shell, (when I try to use iconv function)
`php -d error_reporting=22527 -d display_errors=1 -r 'var_dump(iconv("UTF-8", "UTF-8//IGNORE", "This is the Euro symbol '\''€'\''."));'`

I get the following error:
![image](https://user-images.githubusercontent.com/11773683/29594548-b47d66c8-87ec-11e7-8449-6477d41994d5.png)
`Notice: iconv(): Wrong charset, conversion from UTF-8 to UTF-8//IGNORE is not allowed in Command line code on line 1`

any other character set
`Notice: iconv(): Wrong charset, conversion from UTF-8 to EUC-KR is not allowed in Command line code on line 1`

Please refer to [this issue](https://github.com/docker-library/php/issues/240),

There is no error when using **mb_convert_encoding**. I just think I can use this.

**Comment by richarvey** [comment]
Ok, I'm pushing out the fix for this right now. Expect tag 1.3.1 to fix this
