### ISSUE TITLE
Nginx always return 502

### ISSUE THREAD

**Issue by iqbalprabu** [ngineered/nginx-php-fpm#168]
hi, i pull your image and run in my laptop.
but nginx always return 502, how to solved it ?

> 2017/08/29 05:33:32 [crit] 15#15: *1 connect() to unix:/var/run/php-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 172.17.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "localhost:8085"
> 172.17.0.1 - - [29/Aug/2017:05:33:32 +0000] "GET / HTTP/1.1" 502 568 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
> 172.17.0.1 - - [29/Aug/2017:05:33:33 +0000] "GET /favicon.ico HTTP/1.1" 200 0 "http://localhost:8085/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"

**Comment by richarvey** [comment]
Could you confirm that you have the latest version, run:

`docker rmi richarvey/nginx-php-fpm:latest
`

Then run your command to start the image again. I can't repeat the error, but let's try downloading the latest first and see if that fixes it. A good test would be to run it without any options and see if you get the PHP info page up.

Ric

**Comment by iqbalprabu** [comment]
yes, i have latest image. then i run without any option and can run normaly.
but when i custom any config, this error as above 

this custom config

> FROM richarvey/nginx-php-fpm
> 
> ##remove old config nginx
> RUN rm -rf /etc/nginx/sites-available/default-ssl.conf
> RUN rm -rf /etc/nginx/sites-enabled/default-ssl.conf
> RUN rm -rf /etc/nginx/sites-enabled/default.conf
> 
> ADD conf/pmi-site.conf /etc/nginx/sites-available/pmiweb.conf
> ##ADD conf/pmi-site-ssl.conf /etc/nginx/sites-available/pmiweb-ssl.conf
> ADD conf/backend-site.conf /etc/nginx/sites-available/backend.conf
> ##ADD conf/backend-site-ssl.conf /etc/nginx/sites-available/backend-ssl.conf
> 
> RUN ln -s /etc/nginx/sites-available/pmiweb.conf /etc/nginx/sites-enabled/pmiweb.conf
> RUN ln -s /etc/nginx/sites-available/backend.conf /etc/nginx/sites-enabled/backend.conf
> 
> RUN mkdir -p /var/www/pmi-web
> WORKDIR /var/www/pmi-web
> 
> ADD . /var/www/pmi-web
> RUN cp .env.example .env
> RUN composer install -vvv
> RUN php artisan key:generate
> 
> EXPOSE 443 80 9000
> 
> CMD while true; do sleep 1000; done

**Comment by richarvey** [comment]
Also, check permissions. It's possible the PHP process can't access your files

**Comment by iqbalprabu** [comment]
my config nginx also same with the example in your github.

this is php config

> location ~ \.php$ {
>                 try_files $uri =404;
> 		fastcgi_split_path_info ^(.+\.php)(/.+)$;
> 		fastcgi_pass unix:/var/run/php-fpm.sock;
> 		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
>     		fastcgi_param SCRIPT_NAME $fastcgi_script_name;
> 		fastcgi_index index.php;
> }
>

**Comment by iqbalprabu** [comment]
i can't find this file

> /var/run/php-fpm.sock

**Comment by richarvey** [comment]
It's there in the stock image, so it has to be something to do with the way you're modifying the image. Why do you have this sleep command?

`CMD while true; do sleep 1000; done`

The stock image runs scripts/start.sh as its CMD, this is responsible for starting supervisord which runs nginx and php-fpm.

If php-fpm is not being started that's why you can't find the sock file. This file isn't a flat file it's the Unix socket that gets created when the process is running.

**Comment by iqbalprabu** [comment]
yeah solved with change this

> CMD while true; do sleep 1000; done > CMD ["/start.sh"]

thank you for the time and the answer

**Comment by richarvey** [comment]
you're welcome
