### ISSUE TITLE
Error in docker log

### ISSUE THREAD

**Issue by tapir** [ngineered/nginx-php-fpm#18]
I get a lot of this error when I try to run the stable image

```
sed: -e expression #1, char 18: unknown option to `s'
```
I run mariadb like this
```
docker run --name mariadb -e MYSQL_ROOT_PASSWORD=******** -e MYSQL_DATABASE=ocloud -e MYSQL_USER=ocloud_user -e MYSQL_PASSWORD=********* -d mariadb
```
I run nginx-pgp-fpm as follows:
```
docker run -v /home/cosku/owncloud/www/owncloud-8.1:/usr/share/nginx/html -v /home/cosku/owncloud/ssl:/etc/nginx/ssl -v /home/cosku/owncloud/sites-enabled:/etc/nginx/sites-enabled -p 80:80 --link mariadb:mysql -d richarvey/nginx-php-fpm:stable
```

**Comment by Sam-R** [comment]
The same thing is happening to me. It looks like it's this line to me:
```
 find /usr/share/nginx/html -type f -exec sed -i -e 's/'${replace}'/'${value}'/g' {} \;
```

When running the container in interactive mode, I run 
```
bash -x start.sh
```
It seems to get hung up on this line, which is inside a for loop. My container takes ages to start due to all of the sed errors.

I don't have any idea how to fix it yet though!

**Comment by richarvey** [comment]
I see this also. If you're not using templating use the: -e TEMPLATE_NGINX_HTML=0 flag

I'll look at replacing this script with python and something less likely to error.

Ric

**Comment by tapir** [comment]
I use it like this on my own container
```sed -i -e "s/\${REPLACE}/$VALUE/" /etc/nginx/sites-available/default``` and it works ok.

**Comment by richarvey** [comment]
@tapir I'll give your suggestion a go

**Comment by ptebault** [comment]
This line in start.sh:19 also causes grief when I mount a webroot per your example: https://github.com/ngineered/nginx-php-fpm/blob/master/start.sh

Meaning perhaps, the examples given on hub.docker.com may be incorrect in light of this git pull feature that's currently in the package.

Thankfully it's read-only, but that means that the script then iterates through the (hundred thousand or so) files in that webroot and complains that it has no permission to delete the files.

Once that completes, the container finishes, starts nginx, and all is happy.

**Comment by killerwolf** [comment]
+1 use `-e TEMPLATE_NGINX_HTML=0`

template skipping should be enabled by default.

**Comment by richarvey** [comment]
Guys I'm going to make this disabled by default this afternoon, along with some other updates

**Comment by richarvey** [comment]
Now disabled by default
