### ISSUE TITLE
chown nginx.nginx error

### ISSUE THREAD

**Issue by vwbusguy** [ngineered/nginx-php-fpm#19]
On starting up a container I see the error:

`chown: invalid user: 'nginx.nginx'`

Changing this to `nginx:nginx` should fix it.

**Comment by richarvey** [comment]
Ok I'll give that a test the . is just the old style notation and should work. It could be the packages are updated with www-data as the user

**Comment by richarvey** [comment]
This should now be fixed it was a change in user from nginx to www-data. The dot notation . and the comma : both work its just that I'm old fashioned and use the dot.
