### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by Zyles** [ngineered/nginx-php-fpm#20]
Hi,

Sorry docker noob here. But I get 403 Forbidden with this package when I try to mount a volume on my host machine.

Docker seems to be running as root, so I am not sure why it would happen. It should have read access everywhere no?

Is it 403 on the host machine files, or files inside the container? I am not sure how to debug this.

Any tips?

**Comment by coleca** [comment]
Nginx and php-fpm run as www-data not root, so your volume needs to allow that user access.

**Comment by Zyles** [comment]
Thanks.

**Comment by julianxhokaxhiu** [comment]
@coleca can you explain how? I'm having exactly this issue :) Thank in advance
