### ISSUE TITLE
I like the templates.... but....

### ISSUE THREAD

**Issue by richtera** [ngineered/nginx-php-fpm#28]
If you use the git pull thing it should probably do a git checkout -f to undo the templating. Then the git pull and then reapply the templating. This might be a bit of a problem with git push because the executed templates would be pushed....
Might need a slightly better way. thinking...
Thanks
Andy

**Comment by richarvey** [comment]
open to options best way is to switch them off if not used.

**Comment by richtera** [comment]
:) Ok. My point was really that the pull operation doesn't reapply them :)
The push outputs templated data is a point but unlikely to be a real problem since not many people would modify files on the docker and attempt to push it.
But turning those off is another option.
