### ISSUE TITLE
Suggestion for sed replacement hack in start.sh

### ISSUE THREAD

**Issue by kwilliams** [ngineered/nginx-php-fpm#32]
I'm designing a similar container, and in the process found this awesome utility envsubst ( http://manpages.ubuntu.com/manpages/gutsy/man1/envsubst.1.html )

**Comment by richarvey** [comment]
This looks pretty cool will give it a go

**Comment by jackmcpickle** [comment]
I think I have found a real solution for this. 

See https://github.com/php/php-src/pull/598

Just need to add something like this to the Dockerfile

```Dockerfile
RUN sed -i -e "s/^;clear_env = no$/clear_env = no/" /etc/php5/fpm/pool.d/www.conf
```

and then you will be able to use `$_ENV['DB_HOST']` instead of `$$_DB_HOST_$$`

**Comment by devkinetic** [comment]
@jackmcpickle you would think it's that easy but the container runs PHP 5.5.9. According to https://secure.php.net/manual/ro/install.fpm.configuration.php clear_env was added in 5.5.11 so PHP needs to be upgraded first, and then your `RUN` command.

**Comment by jackmcpickle** [comment]
We have forked it awhile back to run our cms on php7 - also adds nodejs.. 
see https://github.com/sealink/phpdocker

probably a good idea to update php5.5.36 as its the latest security update. 

Maybe a chance to run branches for each version of php? 5.5/5.6/7 ?

**Comment by richarvey** [comment]
Guys,

I'm just built a 5.6.21 version and a 7.0.7. I'll give this a go asap.
