### ISSUE TITLE
php extensions 

### ISSUE THREAD

**Issue by killerwolf** [ngineered/nginx-php-fpm#33]
how to add php extension mongo for example ?

**Comment by richarvey** [comment]
How about I add a feature to allow you to install plugins on the fly?

**Comment by killerwolf** [comment]
Yeah it would be great

**Comment by richarvey** [comment]
This will be rolled in to the next release. Look for the DEBS flag

**Comment by exetico** [comment]
Hi'

How did it go? I hardly need php_sockets but can't find the right way to make it.

**Comment by richarvey** [comment]
Hey, so we now are on php 7.1 built from the official php image.

If you bash into the container you should be able to use the commands to install plugins. I'll document it soon.

Ric

**Comment by exetico** [comment]
@richarvey - Thanks for your answer.
After some time i skipped your docker and did go with nasqueron/nginx-php-fpm - and find out how to add ext's. But, today i tested it again.

It works just like it should, so i'm back at richarvey/nginx-php-fpm :)!

Join) 
docker exec -t -i nginx /bin/bash

Run)
/usr/local/bin/docker-php-ext-configure sockets
/usr/local/bin/docker-php-ext-install sockets

Exit and restart docker)
docker kill nginx
docker start nginx

**Comment by richarvey** [comment]
you dont need to kill the container simply run:

```supervisorctl restart php-fpm```

Ric
