### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by killerwolf** [ngineered/nginx-php-fpm#34]
How about using php5.6 or even php7, is this doable ?

**Comment by richarvey** [comment]
As Ubuntu updates I'll roll this out, I'll check what version will land with 16.04 in April. Debian packaging is a little confusing in its versioning, as 5.5 receives security updates and it's pretty close to 5.6 in features. I'll produce a beta version in the next week that you can test.

**Comment by killerwolf** [comment]
I am using the new php mongodb driver (not the old one called mongo),

https://docs.mongodb.org/ecosystem/drivers/php/#drivers

looks like i can't install it within your container running php5.5

may the reason is it's a PECL package (only), not a deb one.

**Comment by richarvey** [comment]
Hi @killerwolf ,

You can test the richarvey/nginx-php-fom:beta56 and beta70 images now.

I don't believe this solves the PECL issue as there are no debian packages for mongo. I'm looking into a way to solve this now but feel free to try the latest betas

Ric

**Comment by richarvey** [comment]
@killerwolf pecl is a little broken in php 7 on unbuntu 16.04 as soon as its fixed I'll add a -e "PECL_INSTALL=mongoDB" flag

**Comment by killerwolf** [comment]
OK waiting for it then

**Comment by richarvey** [comment]
Guys,

These need to be built in docker hub but there are new containers php 5.6.21 and php 7.0.7 all built on a new streamlined alpine linux base.

**Comment by echobool** [comment]
@richarvey Isn't it a new version? I need to install PHP driver Mongo thanks
