### ISSUE TITLE
Can't get enviroment variables to work as described

### ISSUE THREAD

**Issue by DuncanMarshall** [ngineered/nginx-php-fpm#38]
I'm trying to set up this container and have it be linked to a mysql container, but I can't work out how to get access to the enviroment variables for things like the mysql server's IP, and so on.

I'm launching the mysql container like so:

`sudo docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=yayMySQL -e MYSQL_DATABASE=wordpress -e MYSQL_USER=wordpress_user -e MYSQL_PASSWORD=wordpress_password -d mysql`

And the nginx-php-fpm container like so:

`sudo docker run --name nginx -p 80:80 -e TEMPLATE_NGINX_HTML=1 -v /home/username/www/html:/usr/share/nginx/html --link some-mysql:mysql -d richarvey/nginx-php-fpm`

Inside ~/www/html, I have a file called index.php, with the following code:

`<?php $database_name = $$_MYSQL_ENV_MYSQL_DATABASE_$$; ?>`

In a browser, this yields the error:

`Parse error: syntax error, unexpected '$' in /usr/share/nginx/html/index.php on line 1`

Other variations do the same thing.  PHP just doesn't like those dollar signs in all instances.
`print_r($_ENV);` displays an empty array.  `get_env()` on all the variables mentioned in the documentation yields nothing.

How is this meant to work?

**Comment by coleca** [comment]
You need to pass the environment variables into the PHP FPM config. Something like this before nginx starts is what I do:  


 printenv | xargs -I{} echo {} | awk 'BEGIN { FS = "=" }; { print "env ["$1"] = "$2 }' >> /etc/php5/fpm/pool.d/www.conf

That exports the entire environment to PHP FPM because by default it clears out the environment before it starts.

**Comment by coleca** [comment]
Clicked comment too fast. I meant to say I add that to the start.sh script before supervisor starts up.

**Comment by DuncanMarshall** [comment]
Thanks @coleca, I was just in the process of realizing the templating gets done *when the container starts* as I read your comment.

This being the first real thing I've done with Docker, I don't know what you mean by "the start.sh".  I'm running the container with the docker run command as above.  Is there supposed to be a start.sh script I should know about and that I can add your command to?

To anyone else who suffers form the same confusion as me, the $$_ENV_VARIABLE_$$ tags are written in to your files **as the container starts**.  That's to say, if you put $$_MYSQL_PORT_3306_TCP_ADDR_$$ in to your PHP files, when you run the container, it will actually rewrite those strings in your files to something like "172.17.0.2".

**Comment by coleca** [comment]
Sorry. I meant I cloned the repo, edited the scripts/start.sh script and built my own version of the container.

**Comment by DuncanMarshall** [comment]
Thanks @coleca, worked like a charm!
