### ISSUE TITLE
rm /usr/share/nginx/html/*

### ISSUE THREAD

**Issue by bpavacic** [ngineered/nginx-php-fpm#40]
The line:
rm /usr/share/nginx/html/*
in startup script doesn't delete subdirectories nor .git* files causing "git clone" to fail.
I suggest changing it to 
rm -Rf /usr/share/nginx/html

**Comment by richarvey** [comment]
I'll check this out however the conatiners just been rebuilt on alpine linux from the ground up. I have a feeling this may still exist though.

**Comment by richarvey** [comment]
This should now be resolved with your suggestion. Also the new default directory is /var/www/html jfyi

**Comment by bpavacic** [comment]
Thank you, it seems to be working now.
