### ISSUE TITLE
Can't pull code from git

### ISSUE THREAD

**Issue by caibirdme** [ngineered/nginx-php-fpm#49]
Hi,I was puzzled by `Dynamically Pulling Code from git`.My steps are blow:
* pull image
* ssh-keygen -t rsa -C "my.email" && enter enter...
* add ~/.ssh/id_rsa.pub to github
* `git clone git@my.repo proj` to `proj` dir
* `base64 -w 0 ~/.ssh/id_rsa.pub` and copy the result
* `sudo docker run --name aha -d -v /path/to/proj:/var/www/html -e 'GIT_REPO=git@my.repo' -e 'GIT_BRANCH=develop' -e 'SSH_KEY=paste' -e 'GIT_NAME=myname' -e 'GIT_EMAIL=myemail' --link db:db richarvey/nginx-php-fpm`

and In my `proj` there is just only a `index.php` file which likes this:
```
<?php
$name = 'test';
echo "hello $name";
?>
```

after Running the docker command I can see it is running by `sudo docker ps` but I cannot access the url `host:80`

And when modify the proj remotely and push it ,I cannot run `sudo docker exec -it aha /usr/bin/pull` to pull the latest code,it reports that it uses `/root/.ssh/id_rsa` to verify my identity which looks very strange.
How can I solve this problem?Thx

**Comment by richarvey** [comment]
Can you paste me the output from: 

sudo docker exec -t aha /usr/bin/pull

Please

**Comment by richarvey** [comment]
Also looking at your command its seems you are already pulling the code into the container using the VOLUME -v flag. I'm guessing /path/to/project already contains you code? If so you dont need to pull from git as you already have the code.

Try dropping the volume flag and using the pull and push scripts instead. /root/.ssh/id_rsa is perfectly normal. Inside your container there is only the root and nginx users.

Ric
