### ISSUE TITLE
Questions for ubuntu:14.04

### ISSUE THREAD

**Issue by TomomiSawako** [ngineered/nginx-php-fpm#51]
I'm try to build an different image, so i use ubuntu:14.04
But i'm not found "listen = 127.0.0.1:9000" in /etc/php5/fpm/php-fpm.conf

**Comment by richarvey** [comment]
This is a alpine linux image so swapping the dockerfile to use ubuntu wont work as alpine uses apk to install packages and ubuntu uses apt-get
