### ISSUE TITLE
Alpine linux & nginx version

### ISSUE THREAD

**Issue by titpetric** [ngineered/nginx-php-fpm#56]
After updating to alpine linux, the nginx version provided doesn't provide the realip module:

~~~
nginx: [emerg] unknown directive "set_real_ip_from" in /etc/nginx/sites-enabled/[...]
~~~

**Comment by richarvey** [comment]
I'll take a look into this now and get back to you asap

**Comment by richarvey** [comment]
Looks like this is an issue in alpine linux and there are a couple of open feature requests for it.

Such as:

https://bugs.alpinelinux.org/issues/5712
