### ISSUE TITLE
ERROR: An another FPM instance seems to already listen on /var/run/php-fpm.sock

### ISSUE THREAD

**Issue by swoodford** [ngineered/nginx-php-fpm#60]
After cloning the branch php7, completing a docker build & run as-is, getting issues starting up php-fpm7.

`~/github/nginx-php-fpm  (php7) docker run -ti nginx-php-fpm`
`2016-08-18 17:38:42,558 CRIT Set uid to user 0`
`2016-08-18 17:38:42,564 INFO RPC interface 'supervisor' initialized`
`2016-08-18 17:38:42,565 CRIT Server 'unix_http_server' running without any HTTP authentication checking`
`2016-08-18 17:38:42,565 INFO supervisord started with pid 9`
`2016-08-18 17:38:43,569 INFO spawned: 'php-fpm7' with pid 12`
`2016-08-18 17:38:43,570 INFO spawned: 'nginx' with pid 13`
`2016-08-18 17:38:43,601 INFO exited: php-fpm7 (exit status 0; not expected)`
`2016-08-18 17:38:44,604 INFO spawned: 'php-fpm7' with pid 23`
`2016-08-18 17:38:44,604 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)`
**`[18-Aug-2016 17:38:44] ERROR: An another FPM instance seems to already listen on /var/run/php-fpm.sock`
`[18-Aug-2016 17:38:44] ERROR: FPM initialization failed`
`2016-08-18 17:38:44,631 INFO exited: php-fpm7 (exit status 70; not expected)`**
`2016-08-18 17:38:46,643 INFO spawned: 'php-fpm7' with pid 25`
`[18-Aug-2016 17:38:46] ERROR: An another FPM instance seems to already listen on /var/run/php-fpm.sock`
`[18-Aug-2016 17:38:46] ERROR: FPM initialization failed`
`2016-08-18 17:38:46,670 INFO exited: php-fpm7 (exit status 70; not expected)`
`2016-08-18 17:38:49,679 INFO spawned: 'php-fpm7' with pid 27`
`[18-Aug-2016 17:38:49] ERROR: An another FPM instance seems to already listen on /var/run/php-fpm.sock`
`[18-Aug-2016 17:38:49] ERROR: FPM initialization failed`
`2016-08-18 17:38:49,708 INFO exited: php-fpm7 (exit status 70; not expected)`
`2016-08-18 17:38:50,710 INFO gave up: php-fpm7 entered FATAL state, too many start retries too quickly`

**Comment by infinitysgame** [comment]
Experienced this myself. A couple of things I did to resolve it:

Update the following line in `supervisord.conf`:
from
`command = /usr/sbin/php-fpm7 -c /etc/php`
to
`command = /usr/sbin/php-fpm7 --nodaemonize --fpm-config /etc/php7/php-fpm.conf`

_(Not sure you require `--nodaemonize` switch in the command line above if you apply the changes below)_

and

the following line in the `Dockerfile`:

from
`sed -i -e "s/;daemonize\s*=\s*yes/daemonize = no/g" ${fpm_conf} && \`
to
`sed -i -e "s/;daemonize\s*=\s*yes/daemonize = no/g" /etc/php7/php-fpm.conf && \`

**Comment by richarvey** [comment]
Thanks @infinitysgame We'll look at rolling those suggestions into the code.

Ric

**Comment by infinitysgame** [comment]
@richarvey No. Thank you. Your Dockerfile has been a great guide for building my own images.

**Comment by richarvey** [comment]
I've rolled in some of @infinitysgame suggestions, i haven't swapped the location of the php-fpm.conf as it had a few things missing. But i have updated the supervisor conf in a similar way.

@swoodford my output is now this:
```
2016-08-22 08:17:23,652 CRIT Set uid to user 0
2016-08-22 08:17:23,659 INFO RPC interface 'supervisor' initialized
2016-08-22 08:17:23,659 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2016-08-22 08:17:23,660 INFO supervisord started with pid 9
2016-08-22 08:17:24,662 INFO spawned: 'php-fpm7' with pid 12
2016-08-22 08:17:24,663 INFO spawned: 'nginx' with pid 13
2016-08-22 08:17:25,706 INFO success: php-fpm7 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-08-22 08:17:25,707 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```
Another thing I would suggest to @swoodford is to run it the container with -d instead of -ti you can then use ```docker exec -it <container> bash``` to shell into the container or ``` docker logs -f <container>``` to check the logs, hopefully that gives you a couple more options

**Comment by swoodford** [comment]
Thanks for your quick help @infinitysgame @richarvey !  This seems to be fixed now!!
