### ISSUE TITLE
Do you not have VOLUME directive in Dockerfile for a reason?

### ISSUE THREAD

**Issue by virtuman** [ngineered/nginx-php-fpm#61]
I really like the simplicity of the project, and would like to use it in DEV and in Production environments. I'm wondering if this is intentional that you don't have VOLUME directive in the Dockerfile, which would allow for a more standard workflow on a developer's machine?

I would suggest allowing to bind volume for /var/www/html, or since there's a repo layout proposition than maybe as an option something like /var/www/html/src .. 

or do you not include it for some specific reason?

PS: what i mean by more standard, is that developer can continue to work within local file system, rather than having to work through dockerized volume.

**Comment by richarvey** [comment]
We did have this until recently, I think it was dropped out when testing some of the git features. I agree we should add this back in. I'll get it done asap.

Ric
