### ISSUE TITLE
ZipArchive？

### ISSUE THREAD

**Issue by MeowCold** [ngineered/nginx-php-fpm#62]
![qq 20160825152537](https://cloud.githubusercontent.com/assets/7279597/17960366/3d449626-6ad8-11e6-8a8a-b818c92fe02a.png)
does not exist ZipArchive
ZipArchive must be available

**Comment by richarvey** [comment]
@MeowCold New images are building now this should solve your issue.

**Comment by MeowCold** [comment]
@richarvey Thank you very much for helping me this  who does not understand Dockerfile person。
