### ISSUE TITLE
Would you consider adding dynamic module support into nginx conf?

### ISSUE THREAD

**Issue by virtuman** [ngineered/nginx-php-fpm#63]
Is it possible to use nginx image or package that has geoip and other dynamic modules? It would be great to be able to have that ability. 

ie.  https://www.nginx.com/blog/dynamic-modules-nginx-1-9-11/

or possibly build the entire image from copy nginx:alpine https://github.com/nginxinc/docker-nginx/tree/master/mainline/alpine , it contains all dynamic modules and can be enabled if desired using ENV variables

**Comment by richarvey** [comment]
I like the idea @virtuman I'll take a look

**Comment by richarvey** [comment]
@virtuman I have a test version of php5 with dynamic module support, it would be great if you could test before i merge:

https://github.com/ngineered/nginx-php-fpm/tree/php5-dynamic

**Comment by richarvey** [comment]
Task List:

- [x] Create php5 branch built from nginx:mainline-alpine
- [ ] Complete php5 tests
- [ ] Create php7 branch built from nginx:mainline-alpine
- [ ] Complete php7 tests
- [ ] Create php5-dynamic and php7-dynamic tags and images on docker hub for wider testing
- [ ] Merge Branches
- [ ] clean up branches (github)
- [ ] clean up testing tags (docker hub)

**Comment by richarvey** [comment]
Hi @virtuman the test php5 and php7 images are in docker hub now.

Just use tags php5-dynamic or php7-dynamic when pulling. After wider testing we'll merge into the main images.

For example:

```￼
docker pull richarvey/nginx-php-fpm:php5-dynamic
```

Ric

**Comment by virtuman** [comment]
THANK YOU SO VERY MUCH !!! Much Appreciated !

**Comment by richarvey** [comment]
This has now been completed and merged into the default branches.

So you can now use:

```
docker pull richarvey/nginx-php-fpm:latest
docker pull richarvey/nginx-php-fpm:php5
docker pull richarvey/nginx-php-fpm:php7
```
As before I'll be removing the dynamic tags as testing has finished.
