### ISSUE TITLE
Request to add session support

### ISSUE THREAD

**Issue by jlaswell** [ngineered/nginx-php-fpm#67]
By default, session support doesn't seem to be is not enabled. I know this prevents Laravel applications from working out of the box, but I think this may also affect Symfony's HttpFoundation component.

Would you consider adding `php5-session`/`php7-session` to the defaults?

**Comment by richarvey** [comment]
I'll look at doing this today, I may also add a flag to allow you to point sessions at redis or memcache

**Comment by richarvey** [comment]
@jlaswell it seems no need to do this in php5 however php7 needs the extra package you mention.

I'll be doing an update shortly.

**Comment by richarvey** [comment]
PHP7 now has session support, enjoy ;)

**Comment by jlaswell** [comment]
Awesome! Thanks!!
