### ISSUE TITLE
Default redirect to /index.php

### ISSUE THREAD

**Issue by SamMousa** [ngineered/nginx-php-fpm#74]
I think nowadays most if not all PHP projects will use some kind of url rewriting that works by simply redirecting all files that are not found to an entry script.

Given some assumptions on configuration:
1. Your whole PHP project is outside yourwebroot.
2. There is 1 `index.php` file in your webroot that is the entry point for the application.
3. Any files in the webroot can be considered public (ie css / js / images) and should be served directly.
4. Any URLs that are not found should be redirected to `index.php` to give the PHP application the option to handle the request.

The only change required to support this is to replace in the default configuration:
````	
location / {
    # First attempt to serve request as file, then
    # as directory, then fall back to index.html
    try_files $uri $uri/ =404;
}
````
With:
````	
location / {
    # First attempt to serve request as file, then
    # as directory, then fall back to index.html
    try_files $uri $uri/ /index.php?$args;
}
````

Some side notes:
1. I don't think the location / block is needed, you can just put it directly in the server.
2. I don't think the try_files needs to be repeated inside the php location block.

**Comment by richarvey** [comment]
Hey @SamMousa,

Thanks for this, I know things like craft CMS usages this, but not sure if drupal or wp work in the same way. This is why we have the support for a custom nginx config. The config included will work with custom code or a single PHP page, the idea is to keep it generic.

Ric

**Comment by SamMousa** [comment]
I've done some research on the different PHP frameworks and common apps.

Frameworks supporting / requiring redirect to `ROOT/index.php` for files that are not found:
- Yii2
- Wordpress (https://codex.wordpress.org/Nginx#General_WordPress_rules)
- Drupal (https://www.nginx.com/resources/wiki/start/topics/recipes/drupal/)
- CodeIgniter (https://www.nginx.com/resources/wiki/start/topics/recipes/codeigniter/)
- Laravel (https://www.digitalocean.com/community/tutorials/how-to-install-laravel-with-an-nginx-web-server-on-ubuntu-14-04)
- CakePHP (https://book.cakephp.org/2.0/en/installation/url-rewriting.html)
- Zend (https://www.nginx.com/resources/wiki/start/topics/recipes/zend/)
- Slim framework (http://docs.slimframework.com/routing/rewrite/#nginx)


Frameworks that are different:
- Symfony (http://symfony.com/doc/current/setup/web_server_configuration.html) **Uses `app.php` instead of `index.php`**

**Comment by SamMousa** [comment]
@richarvey Could you look at this again please?

**Comment by SamMousa** [comment]
@richarvey bump

**Comment by Braintelligence** [comment]
@SamMousa Hey, I'm not sure, so maybe you could help me out: 
Is this change implemented yet in any way or do I have to set this by myself?

**Comment by SamMousa** [comment]
Not when I last checked. I no longer use this.

**Comment by Braintelligence** [comment]
@SamMousa 
I'm really confused here...
When I try to mount the /etc/nginx folder, so I can access it from the host, the docker container won't initialize the folder with nginx files.

Do you have any recommendation for docker containers to run general php-based apps, like wordpress?

**Comment by SamMousa** [comment]
You need to build your own image; or in the case of wordpress, use theirs.
With wordpress you're in trouble with the user uploads though; they need special handling. 

Good luck figuring it out!

**Comment by Braintelligence** [comment]
@SamMousa Yeah, I'll try to use the official WordPress image for now. Thank you for the hints!
