### ISSUE TITLE
Promote PHP7 to master

### ISSUE THREAD

**Issue by richarvey** [ngineered/nginx-php-fpm#75]
As PHP5 becomes (all be it) soft end of life in December we need to start staging the master branch to become the master branch.

**Comment by richarvey** [comment]
created php5 branch in git and made docker hub build tag from that

**Comment by richarvey** [comment]
Need to Add PHP7 is now default to readme and promote when change happens

**Comment by ErikFontanel** [comment]
I noticed that the PHP7 branch pulls Alpine 3.4, hard coded. Not edge or latest tags, like master), Why is that? I had some trouble today because I learned that Alpine 3.4 comes with Nginx 1.10.2 instead of 1.11.x.

**Comment by richarvey** [comment]
It should be pulling edge hard coded. Its the only way to satisfy install deps without breaking.

**Comment by richarvey** [comment]
Switched master to PHP7
