### ISSUE TITLE
Exif PHP extension

### ISSUE THREAD

**Issue by ChristopheLecroq** [ngineered/nginx-php-fpm#80]
Hi,

I have a problem with the exif extension when I run my website on nginx-php-fpm container : 

Error: Call to undefined function PHPExif\Adapter\exif_read_data()

My website runs well on my non-Docker installation (Archlinux/Nginx/PHP-FPM). Any ideas ? I've tried some tweaks but I didn't find nothing related to extensions.

Thank you !

**Comment by richarvey** [comment]
Ill take a look at this asap

**Comment by richarvey** [comment]
Hi @ChristopheLecroq this should now be resolved if you pull the new images. I've added php5-exif support and php7-exif support.

**Comment by ChristopheLecroq** [comment]
Thank you very much ! I really appreciate :)
