### ISSUE TITLE
php5-soap in php7 build

### ISSUE THREAD

**Issue by stuartz-VernonCo** [ngineered/nginx-php-fpm#84]
Ran into issue of SoapClient not found on :php7  Looks like the extension for soap was missed as it is still php5.

**Comment by blerko** [comment]
Hello, yes that looks like a typo in the Dockerfile, I will get that fixed as soon as I can

**Comment by blerko** [comment]
Sorry for the delay in getting this fixed, I have rebuilt the php7 branch. There are a few more changes there than I expected, but this should fix the php5-soap issue.
