### ISSUE TITLE
mysql.default_socket missing?

### ISSUE THREAD

**Issue by victor-lund** [ngineered/nginx-php-fpm#85]
I installed this image (php7-bransch) and it looks like a phpinfo(); command gives me the following output:

```
mysql.default_socket	/var/run/mysqld/mysqld.sock	/var/run/mysqld/mysqld.sock
```

However, when trying to connect to my database it appeared as if there was a problem with the socket so I had a look inside the container and could not find the /var/run/mysqld/ folder.

What am i missing?

Edit: I attached my log from nginx-php-fpm:

[nginx-php-fpm-log.txt](https://github.com/ngineered/nginx-php-fpm/files/521205/nginx-php-fpm-log.txt)

**Comment by blerko** [comment]
Hello,

Am I right in thinking that you are running mysql in a separate container?

**Comment by victor-lund** [comment]
That's correct!

**Comment by blerko** [comment]
So I believe that the mysqld.sock is only available if you are running mysql locally (within the same container). Mysql server creates that socket file when it starts, you should see it in the mysql container you are running.  So you need to make a connection to the mysql container, how you do that depends on how you have set things up, but you should be able to connect to the mysql container across the network.

**Comment by victor-lund** [comment]
Thank you - now solved the issue.

Closing
