### ISSUE TITLE
letsencrypt-setup changes $WEBROOT back to default path

### ISSUE THREAD

**Issue by aifarfa** [ngineered/nginx-php-fpm#89]
when i ran docker with WEBROOT specified

```bash
docker run --name web -p 80:80 -p 443:443 -e 'WEBROOT=/var/www/html/public' -e 'DOMAIN=mydomain.com -e 'ETC=..' -d richarvey/nginx-php-fpm:latest

docker exec -t web letsencrypt-setup
```

then i got 404 response from `https://` (tcp/80 works just fine)

i found that the `/etc/nginx/sites-enabled/default-ssl.conf` has been changed from `/var/www/html/public` to `/var/www/html`

**Comment by richarvey** [comment]
Ahh ok,

good spot, I'll look at fixing this asap
