### ISSUE TITLE
php mail / sendmail doesn't work

### ISSUE THREAD

**Issue by aamche** [ngineered/nginx-php-fpm#93]
Error: "sendmail: can't connect to remote host (127.0.0.1): Connection refused"

Steps to reproduce: Use php mail function or the sendmail function, check logs for error. It seems sendmail is installed. I can run it from the console, but returns the above error. 

OS: Ubuntu 16.04
Other containers jwilder/nginx-proxy | thomastweets/docker-letsencrypt-nginx-proxy-companion

**Comment by icy** [comment]
the sendmail daemon is not started by default

**Comment by victor-lund** [comment]
@icy I have thet same issue - how do i start it?

**Comment by aamche** [comment]
@victor-lund 
Probably a start script, although I've not actually attempted it.
https://github.com/ngineered/nginx-php-fpm/blob/master/docs/scripting_templating.md

**Comment by icy** [comment]
@victor-lund My team is using an external mail service instead (e.g, amazon SES). You need to use `RUN_SCRIPTS=1` ( as @aamche  mentioned ) to start a sendmail daemon (e.g, exim4 or postfix.)
