### ISSUE TITLE
PHP7 Does not have php alias.

### ISSUE THREAD

**Issue by SamMousa** [ngineered/nginx-php-fpm#96]
When using the php7 tag the php cli is not available as `php`, instead it is only available as `php7` which breaks things like composer.

**Comment by SamMousa** [comment]
https://bugs.alpinelinux.org/issues/6450

**Comment by prometherion** [comment]
+1

**Comment by richarvey** [comment]
Looks likes this may have been resolved upstream? I'll re-roll the packages today
