### ISSUE TITLE
Just out of cruiosity - has anyone tried to use this image in PROD env with high traffic?

### ISSUE THREAD

**Issue by virtuman** [ngineered/nginx-php-fpm#97]
Image looks pretty simple and good, has anyone ever tried using it in production environment? is it able to sustain high load?

**Comment by Coobers** [comment]
Yes, it leaks a lot of memory. We did a frequent restarts to sustain it, a global docker problem.
Otherwise speed scales pretty well, but fpm and nginx require adjusting, because they run multiple processes, which is a bottleneck on single instance.

**Comment by richarvey** [comment]
@Coobers do you have any info on your tweaks that we can roll into this?

**Comment by Coobers** [comment]
We'll have some in future, to control multi-threating processes for fpm and nginx and fixes for gettext. No pull date yet.
